namespace gf_materiais.forms
{
    partial class Fornecedor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Fornecedor));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.nomefornecedorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.voltarbotao = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.calendarioNascimento = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.enderecoFornecedorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cnpjFornecedorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cpfFornecdorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.telfornecedorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.emailFornecedorTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RegistrarForncedor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TabelasFornecedor = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.remover = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TabelasFornecedor)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.LightSlateGray;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.remover);
            this.bunifuPanel1.Controls.Add(this.nomefornecedorTxt);
            this.bunifuPanel1.Controls.Add(this.voltarbotao);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel11);
            this.bunifuPanel1.Controls.Add(this.calendarioNascimento);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel1.Controls.Add(this.enderecoFornecedorTxt);
            this.bunifuPanel1.Controls.Add(this.cnpjFornecedorTxt);
            this.bunifuPanel1.Controls.Add(this.cpfFornecdorTxt);
            this.bunifuPanel1.Controls.Add(this.telfornecedorTxt);
            this.bunifuPanel1.Controls.Add(this.emailFornecedorTxt);
            this.bunifuPanel1.Controls.Add(this.RegistrarForncedor);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(396, 450);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // nomefornecedorTxt
            // 
            this.nomefornecedorTxt.AcceptsReturn = false;
            this.nomefornecedorTxt.AcceptsTab = false;
            this.nomefornecedorTxt.AnimationSpeed = 200;
            this.nomefornecedorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomefornecedorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomefornecedorTxt.AutoSizeHeight = true;
            this.nomefornecedorTxt.BackColor = System.Drawing.Color.Transparent;
            this.nomefornecedorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomefornecedorTxt.BackgroundImage")));
            this.nomefornecedorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nomefornecedorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomefornecedorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nomefornecedorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.nomefornecedorTxt.BorderRadius = 23;
            this.nomefornecedorTxt.BorderThickness = 1;
            this.nomefornecedorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nomefornecedorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomefornecedorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomefornecedorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nomefornecedorTxt.DefaultText = "";
            this.nomefornecedorTxt.FillColor = System.Drawing.Color.White;
            this.nomefornecedorTxt.HideSelection = true;
            this.nomefornecedorTxt.IconLeft = null;
            this.nomefornecedorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomefornecedorTxt.IconPadding = 10;
            this.nomefornecedorTxt.IconRight = null;
            this.nomefornecedorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomefornecedorTxt.Lines = new string[0];
            this.nomefornecedorTxt.Location = new System.Drawing.Point(22, 36);
            this.nomefornecedorTxt.MaxLength = 32767;
            this.nomefornecedorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomefornecedorTxt.Modified = false;
            this.nomefornecedorTxt.Multiline = false;
            this.nomefornecedorTxt.Name = "nomefornecedorTxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomefornecedorTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomefornecedorTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomefornecedorTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomefornecedorTxt.OnIdleState = stateProperties4;
            this.nomefornecedorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.nomefornecedorTxt.PasswordChar = '\0';
            this.nomefornecedorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.nomefornecedorTxt.PlaceholderText = "Nome";
            this.nomefornecedorTxt.ReadOnly = false;
            this.nomefornecedorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomefornecedorTxt.SelectedText = "";
            this.nomefornecedorTxt.SelectionLength = 0;
            this.nomefornecedorTxt.SelectionStart = 0;
            this.nomefornecedorTxt.ShortcutsEnabled = true;
            this.nomefornecedorTxt.Size = new System.Drawing.Size(135, 30);
            this.nomefornecedorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomefornecedorTxt.TabIndex = 23;
            this.nomefornecedorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomefornecedorTxt.TextMarginBottom = 0;
            this.nomefornecedorTxt.TextMarginLeft = 3;
            this.nomefornecedorTxt.TextMarginTop = 1;
            this.nomefornecedorTxt.TextPlaceholder = "Nome";
            this.nomefornecedorTxt.UseSystemPasswordChar = false;
            this.nomefornecedorTxt.WordWrap = true;
            // 
            // voltarbotao
            // 
            this.voltarbotao.AllowAnimations = true;
            this.voltarbotao.AllowMouseEffects = true;
            this.voltarbotao.AllowToggling = false;
            this.voltarbotao.AnimationSpeed = 200;
            this.voltarbotao.AutoGenerateColors = false;
            this.voltarbotao.AutoRoundBorders = false;
            this.voltarbotao.AutoSizeLeftIcon = true;
            this.voltarbotao.AutoSizeRightIcon = true;
            this.voltarbotao.BackColor = System.Drawing.Color.Transparent;
            this.voltarbotao.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.voltarbotao.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("voltarbotao.BackgroundImage")));
            this.voltarbotao.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.ButtonText = "Voltar";
            this.voltarbotao.ButtonTextMarginLeft = 0;
            this.voltarbotao.ColorContrastOnClick = 45;
            this.voltarbotao.ColorContrastOnHover = 45;
            this.voltarbotao.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.voltarbotao.CustomizableEdges = borderEdges2;
            this.voltarbotao.DialogResult = System.Windows.Forms.DialogResult.None;
            this.voltarbotao.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.voltarbotao.DisabledFillColor = System.Drawing.Color.Empty;
            this.voltarbotao.DisabledForecolor = System.Drawing.Color.Empty;
            this.voltarbotao.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.voltarbotao.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.voltarbotao.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.IconLeft = null;
            this.voltarbotao.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.voltarbotao.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.voltarbotao.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.voltarbotao.IconMarginLeft = 11;
            this.voltarbotao.IconPadding = 10;
            this.voltarbotao.IconRight = null;
            this.voltarbotao.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.voltarbotao.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.voltarbotao.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.voltarbotao.IconSize = 25;
            this.voltarbotao.IdleBorderColor = System.Drawing.Color.Empty;
            this.voltarbotao.IdleBorderRadius = 0;
            this.voltarbotao.IdleBorderThickness = 0;
            this.voltarbotao.IdleFillColor = System.Drawing.Color.Empty;
            this.voltarbotao.IdleIconLeftImage = null;
            this.voltarbotao.IdleIconRightImage = null;
            this.voltarbotao.IndicateFocus = false;
            this.voltarbotao.Location = new System.Drawing.Point(130, 328);
            this.voltarbotao.Name = "voltarbotao";
            this.voltarbotao.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.voltarbotao.OnDisabledState.BorderRadius = 17;
            this.voltarbotao.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnDisabledState.BorderThickness = 1;
            this.voltarbotao.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.voltarbotao.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.voltarbotao.OnDisabledState.IconLeftImage = null;
            this.voltarbotao.OnDisabledState.IconRightImage = null;
            this.voltarbotao.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.voltarbotao.onHoverState.BorderRadius = 17;
            this.voltarbotao.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.onHoverState.BorderThickness = 1;
            this.voltarbotao.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.voltarbotao.onHoverState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.onHoverState.IconLeftImage = null;
            this.voltarbotao.onHoverState.IconRightImage = null;
            this.voltarbotao.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.voltarbotao.OnIdleState.BorderRadius = 17;
            this.voltarbotao.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnIdleState.BorderThickness = 1;
            this.voltarbotao.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.voltarbotao.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.OnIdleState.IconLeftImage = null;
            this.voltarbotao.OnIdleState.IconRightImage = null;
            this.voltarbotao.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.voltarbotao.OnPressedState.BorderRadius = 17;
            this.voltarbotao.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnPressedState.BorderThickness = 1;
            this.voltarbotao.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.voltarbotao.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.OnPressedState.IconLeftImage = null;
            this.voltarbotao.OnPressedState.IconRightImage = null;
            this.voltarbotao.Size = new System.Drawing.Size(54, 30);
            this.voltarbotao.TabIndex = 9;
            this.voltarbotao.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.voltarbotao.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.voltarbotao.TextMarginLeft = 0;
            this.voltarbotao.TextPadding = new System.Windows.Forms.Padding(0);
            this.voltarbotao.UseDefaultRadiusAndThickness = true;
            this.voltarbotao.Click += new System.EventHandler(this.voltarbotao_Click);
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel11.Location = new System.Drawing.Point(22, 15);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(33, 15);
            this.bunifuLabel11.TabIndex = 22;
            this.bunifuLabel11.Text = "Nome";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // calendarioNascimento
            // 
            this.calendarioNascimento.BackColor = System.Drawing.Color.White;
            this.calendarioNascimento.BorderColor = System.Drawing.Color.Silver;
            this.calendarioNascimento.BorderRadius = 17;
            this.calendarioNascimento.Color = System.Drawing.Color.Silver;
            this.calendarioNascimento.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.calendarioNascimento.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.calendarioNascimento.DisabledColor = System.Drawing.Color.Gray;
            this.calendarioNascimento.DisplayWeekNumbers = false;
            this.calendarioNascimento.DPHeight = 0;
            this.calendarioNascimento.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.calendarioNascimento.FillDatePicker = false;
            this.calendarioNascimento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.calendarioNascimento.ForeColor = System.Drawing.Color.Black;
            this.calendarioNascimento.Icon = ((System.Drawing.Image)(resources.GetObject("calendarioNascimento.Icon")));
            this.calendarioNascimento.IconColor = System.Drawing.Color.Gray;
            this.calendarioNascimento.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.calendarioNascimento.LeftTextMargin = 5;
            this.calendarioNascimento.Location = new System.Drawing.Point(216, 36);
            this.calendarioNascimento.MinimumSize = new System.Drawing.Size(4, 32);
            this.calendarioNascimento.Name = "calendarioNascimento";
            this.calendarioNascimento.Size = new System.Drawing.Size(135, 32);
            this.calendarioNascimento.TabIndex = 21;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(216, 80);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(49, 15);
            this.bunifuLabel7.TabIndex = 20;
            this.bunifuLabel7.Text = "Endereço";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(216, 15);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(91, 15);
            this.bunifuLabel6.TabIndex = 19;
            this.bunifuLabel6.Text = "Data Nascimento";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // enderecoFornecedorTxt
            // 
            this.enderecoFornecedorTxt.AcceptsReturn = false;
            this.enderecoFornecedorTxt.AcceptsTab = false;
            this.enderecoFornecedorTxt.AnimationSpeed = 200;
            this.enderecoFornecedorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.enderecoFornecedorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.enderecoFornecedorTxt.AutoSizeHeight = true;
            this.enderecoFornecedorTxt.BackColor = System.Drawing.Color.Transparent;
            this.enderecoFornecedorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("enderecoFornecedorTxt.BackgroundImage")));
            this.enderecoFornecedorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.enderecoFornecedorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.enderecoFornecedorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.enderecoFornecedorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.enderecoFornecedorTxt.BorderRadius = 23;
            this.enderecoFornecedorTxt.BorderThickness = 1;
            this.enderecoFornecedorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.enderecoFornecedorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.enderecoFornecedorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.enderecoFornecedorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.enderecoFornecedorTxt.DefaultText = "";
            this.enderecoFornecedorTxt.FillColor = System.Drawing.Color.White;
            this.enderecoFornecedorTxt.HideSelection = true;
            this.enderecoFornecedorTxt.IconLeft = null;
            this.enderecoFornecedorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.enderecoFornecedorTxt.IconPadding = 10;
            this.enderecoFornecedorTxt.IconRight = null;
            this.enderecoFornecedorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.enderecoFornecedorTxt.Lines = new string[0];
            this.enderecoFornecedorTxt.Location = new System.Drawing.Point(216, 101);
            this.enderecoFornecedorTxt.MaxLength = 32767;
            this.enderecoFornecedorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.enderecoFornecedorTxt.Modified = false;
            this.enderecoFornecedorTxt.Multiline = false;
            this.enderecoFornecedorTxt.Name = "enderecoFornecedorTxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.enderecoFornecedorTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.enderecoFornecedorTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.enderecoFornecedorTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.enderecoFornecedorTxt.OnIdleState = stateProperties8;
            this.enderecoFornecedorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.enderecoFornecedorTxt.PasswordChar = '\0';
            this.enderecoFornecedorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.enderecoFornecedorTxt.PlaceholderText = "Endereço";
            this.enderecoFornecedorTxt.ReadOnly = false;
            this.enderecoFornecedorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.enderecoFornecedorTxt.SelectedText = "";
            this.enderecoFornecedorTxt.SelectionLength = 0;
            this.enderecoFornecedorTxt.SelectionStart = 0;
            this.enderecoFornecedorTxt.ShortcutsEnabled = true;
            this.enderecoFornecedorTxt.Size = new System.Drawing.Size(135, 30);
            this.enderecoFornecedorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.enderecoFornecedorTxt.TabIndex = 18;
            this.enderecoFornecedorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.enderecoFornecedorTxt.TextMarginBottom = 0;
            this.enderecoFornecedorTxt.TextMarginLeft = 3;
            this.enderecoFornecedorTxt.TextMarginTop = 1;
            this.enderecoFornecedorTxt.TextPlaceholder = "Endereço";
            this.enderecoFornecedorTxt.UseSystemPasswordChar = false;
            this.enderecoFornecedorTxt.WordWrap = true;
            // 
            // cnpjFornecedorTxt
            // 
            this.cnpjFornecedorTxt.AcceptsReturn = false;
            this.cnpjFornecedorTxt.AcceptsTab = false;
            this.cnpjFornecedorTxt.AnimationSpeed = 200;
            this.cnpjFornecedorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cnpjFornecedorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cnpjFornecedorTxt.AutoSizeHeight = true;
            this.cnpjFornecedorTxt.BackColor = System.Drawing.Color.Transparent;
            this.cnpjFornecedorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cnpjFornecedorTxt.BackgroundImage")));
            this.cnpjFornecedorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cnpjFornecedorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cnpjFornecedorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cnpjFornecedorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.cnpjFornecedorTxt.BorderRadius = 23;
            this.cnpjFornecedorTxt.BorderThickness = 1;
            this.cnpjFornecedorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cnpjFornecedorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cnpjFornecedorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cnpjFornecedorTxt.DefaultText = "";
            this.cnpjFornecedorTxt.FillColor = System.Drawing.Color.White;
            this.cnpjFornecedorTxt.HideSelection = true;
            this.cnpjFornecedorTxt.IconLeft = null;
            this.cnpjFornecedorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedorTxt.IconPadding = 10;
            this.cnpjFornecedorTxt.IconRight = null;
            this.cnpjFornecedorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cnpjFornecedorTxt.Lines = new string[0];
            this.cnpjFornecedorTxt.Location = new System.Drawing.Point(216, 167);
            this.cnpjFornecedorTxt.MaxLength = 32767;
            this.cnpjFornecedorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cnpjFornecedorTxt.Modified = false;
            this.cnpjFornecedorTxt.Multiline = false;
            this.cnpjFornecedorTxt.Name = "cnpjFornecedorTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedorTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cnpjFornecedorTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedorTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cnpjFornecedorTxt.OnIdleState = stateProperties12;
            this.cnpjFornecedorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.cnpjFornecedorTxt.PasswordChar = '\0';
            this.cnpjFornecedorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.cnpjFornecedorTxt.PlaceholderText = "Cnpj";
            this.cnpjFornecedorTxt.ReadOnly = false;
            this.cnpjFornecedorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cnpjFornecedorTxt.SelectedText = "";
            this.cnpjFornecedorTxt.SelectionLength = 0;
            this.cnpjFornecedorTxt.SelectionStart = 0;
            this.cnpjFornecedorTxt.ShortcutsEnabled = true;
            this.cnpjFornecedorTxt.Size = new System.Drawing.Size(135, 30);
            this.cnpjFornecedorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cnpjFornecedorTxt.TabIndex = 16;
            this.cnpjFornecedorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cnpjFornecedorTxt.TextMarginBottom = 0;
            this.cnpjFornecedorTxt.TextMarginLeft = 3;
            this.cnpjFornecedorTxt.TextMarginTop = 1;
            this.cnpjFornecedorTxt.TextPlaceholder = "Cnpj";
            this.cnpjFornecedorTxt.UseSystemPasswordChar = false;
            this.cnpjFornecedorTxt.WordWrap = true;
            // 
            // cpfFornecdorTxt
            // 
            this.cpfFornecdorTxt.AcceptsReturn = false;
            this.cpfFornecdorTxt.AcceptsTab = false;
            this.cpfFornecdorTxt.AnimationSpeed = 200;
            this.cpfFornecdorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cpfFornecdorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cpfFornecdorTxt.AutoSizeHeight = true;
            this.cpfFornecdorTxt.BackColor = System.Drawing.Color.Transparent;
            this.cpfFornecdorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cpfFornecdorTxt.BackgroundImage")));
            this.cpfFornecdorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cpfFornecdorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cpfFornecdorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cpfFornecdorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.cpfFornecdorTxt.BorderRadius = 23;
            this.cpfFornecdorTxt.BorderThickness = 1;
            this.cpfFornecdorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cpfFornecdorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cpfFornecdorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfFornecdorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cpfFornecdorTxt.DefaultText = "";
            this.cpfFornecdorTxt.FillColor = System.Drawing.Color.White;
            this.cpfFornecdorTxt.HideSelection = true;
            this.cpfFornecdorTxt.IconLeft = null;
            this.cpfFornecdorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfFornecdorTxt.IconPadding = 10;
            this.cpfFornecdorTxt.IconRight = null;
            this.cpfFornecdorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpfFornecdorTxt.Lines = new string[0];
            this.cpfFornecdorTxt.Location = new System.Drawing.Point(130, 229);
            this.cpfFornecdorTxt.MaxLength = 32767;
            this.cpfFornecdorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.cpfFornecdorTxt.Modified = false;
            this.cpfFornecdorTxt.Multiline = false;
            this.cpfFornecdorTxt.Name = "cpfFornecdorTxt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfFornecdorTxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cpfFornecdorTxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfFornecdorTxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpfFornecdorTxt.OnIdleState = stateProperties16;
            this.cpfFornecdorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.cpfFornecdorTxt.PasswordChar = '\0';
            this.cpfFornecdorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.cpfFornecdorTxt.PlaceholderText = "Cpf";
            this.cpfFornecdorTxt.ReadOnly = false;
            this.cpfFornecdorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cpfFornecdorTxt.SelectedText = "";
            this.cpfFornecdorTxt.SelectionLength = 0;
            this.cpfFornecdorTxt.SelectionStart = 0;
            this.cpfFornecdorTxt.ShortcutsEnabled = true;
            this.cpfFornecdorTxt.Size = new System.Drawing.Size(135, 30);
            this.cpfFornecdorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cpfFornecdorTxt.TabIndex = 15;
            this.cpfFornecdorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cpfFornecdorTxt.TextMarginBottom = 0;
            this.cpfFornecdorTxt.TextMarginLeft = 3;
            this.cpfFornecdorTxt.TextMarginTop = 1;
            this.cpfFornecdorTxt.TextPlaceholder = "Cpf";
            this.cpfFornecdorTxt.UseSystemPasswordChar = false;
            this.cpfFornecdorTxt.WordWrap = true;
            // 
            // telfornecedorTxt
            // 
            this.telfornecedorTxt.AcceptsReturn = false;
            this.telfornecedorTxt.AcceptsTab = false;
            this.telfornecedorTxt.AnimationSpeed = 200;
            this.telfornecedorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.telfornecedorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.telfornecedorTxt.AutoSizeHeight = true;
            this.telfornecedorTxt.BackColor = System.Drawing.Color.Transparent;
            this.telfornecedorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("telfornecedorTxt.BackgroundImage")));
            this.telfornecedorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.telfornecedorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.telfornecedorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.telfornecedorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.telfornecedorTxt.BorderRadius = 23;
            this.telfornecedorTxt.BorderThickness = 1;
            this.telfornecedorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.telfornecedorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.telfornecedorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.telfornecedorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.telfornecedorTxt.DefaultText = "";
            this.telfornecedorTxt.FillColor = System.Drawing.Color.White;
            this.telfornecedorTxt.HideSelection = true;
            this.telfornecedorTxt.IconLeft = null;
            this.telfornecedorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.telfornecedorTxt.IconPadding = 10;
            this.telfornecedorTxt.IconRight = null;
            this.telfornecedorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.telfornecedorTxt.Lines = new string[0];
            this.telfornecedorTxt.Location = new System.Drawing.Point(22, 167);
            this.telfornecedorTxt.MaxLength = 32767;
            this.telfornecedorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.telfornecedorTxt.Modified = false;
            this.telfornecedorTxt.Multiline = false;
            this.telfornecedorTxt.Name = "telfornecedorTxt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telfornecedorTxt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.telfornecedorTxt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telfornecedorTxt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telfornecedorTxt.OnIdleState = stateProperties20;
            this.telfornecedorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.telfornecedorTxt.PasswordChar = '\0';
            this.telfornecedorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.telfornecedorTxt.PlaceholderText = "Telefone";
            this.telfornecedorTxt.ReadOnly = false;
            this.telfornecedorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.telfornecedorTxt.SelectedText = "";
            this.telfornecedorTxt.SelectionLength = 0;
            this.telfornecedorTxt.SelectionStart = 0;
            this.telfornecedorTxt.ShortcutsEnabled = true;
            this.telfornecedorTxt.Size = new System.Drawing.Size(135, 30);
            this.telfornecedorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.telfornecedorTxt.TabIndex = 14;
            this.telfornecedorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.telfornecedorTxt.TextMarginBottom = 0;
            this.telfornecedorTxt.TextMarginLeft = 3;
            this.telfornecedorTxt.TextMarginTop = 1;
            this.telfornecedorTxt.TextPlaceholder = "Telefone";
            this.telfornecedorTxt.UseSystemPasswordChar = false;
            this.telfornecedorTxt.WordWrap = true;
            // 
            // emailFornecedorTxt
            // 
            this.emailFornecedorTxt.AcceptsReturn = false;
            this.emailFornecedorTxt.AcceptsTab = false;
            this.emailFornecedorTxt.AnimationSpeed = 200;
            this.emailFornecedorTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailFornecedorTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailFornecedorTxt.AutoSizeHeight = true;
            this.emailFornecedorTxt.BackColor = System.Drawing.Color.Transparent;
            this.emailFornecedorTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailFornecedorTxt.BackgroundImage")));
            this.emailFornecedorTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.emailFornecedorTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailFornecedorTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.emailFornecedorTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.emailFornecedorTxt.BorderRadius = 23;
            this.emailFornecedorTxt.BorderThickness = 1;
            this.emailFornecedorTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.emailFornecedorTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailFornecedorTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedorTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailFornecedorTxt.DefaultText = "";
            this.emailFornecedorTxt.FillColor = System.Drawing.Color.White;
            this.emailFornecedorTxt.HideSelection = true;
            this.emailFornecedorTxt.IconLeft = null;
            this.emailFornecedorTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedorTxt.IconPadding = 10;
            this.emailFornecedorTxt.IconRight = null;
            this.emailFornecedorTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailFornecedorTxt.Lines = new string[0];
            this.emailFornecedorTxt.Location = new System.Drawing.Point(22, 101);
            this.emailFornecedorTxt.MaxLength = 32767;
            this.emailFornecedorTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailFornecedorTxt.Modified = false;
            this.emailFornecedorTxt.Multiline = false;
            this.emailFornecedorTxt.Name = "emailFornecedorTxt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedorTxt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailFornecedorTxt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedorTxt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailFornecedorTxt.OnIdleState = stateProperties24;
            this.emailFornecedorTxt.Padding = new System.Windows.Forms.Padding(3);
            this.emailFornecedorTxt.PasswordChar = '\0';
            this.emailFornecedorTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.emailFornecedorTxt.PlaceholderText = "Email";
            this.emailFornecedorTxt.ReadOnly = false;
            this.emailFornecedorTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailFornecedorTxt.SelectedText = "";
            this.emailFornecedorTxt.SelectionLength = 0;
            this.emailFornecedorTxt.SelectionStart = 0;
            this.emailFornecedorTxt.ShortcutsEnabled = true;
            this.emailFornecedorTxt.Size = new System.Drawing.Size(135, 30);
            this.emailFornecedorTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailFornecedorTxt.TabIndex = 13;
            this.emailFornecedorTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailFornecedorTxt.TextMarginBottom = 0;
            this.emailFornecedorTxt.TextMarginLeft = 3;
            this.emailFornecedorTxt.TextMarginTop = 1;
            this.emailFornecedorTxt.TextPlaceholder = "Email";
            this.emailFornecedorTxt.UseSystemPasswordChar = false;
            this.emailFornecedorTxt.WordWrap = true;
            // 
            // RegistrarForncedor
            // 
            this.RegistrarForncedor.AllowAnimations = true;
            this.RegistrarForncedor.AllowMouseEffects = true;
            this.RegistrarForncedor.AllowToggling = false;
            this.RegistrarForncedor.AnimationSpeed = 200;
            this.RegistrarForncedor.AutoGenerateColors = false;
            this.RegistrarForncedor.AutoRoundBorders = false;
            this.RegistrarForncedor.AutoSizeLeftIcon = true;
            this.RegistrarForncedor.AutoSizeRightIcon = true;
            this.RegistrarForncedor.BackColor = System.Drawing.Color.Transparent;
            this.RegistrarForncedor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.RegistrarForncedor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegistrarForncedor.BackgroundImage")));
            this.RegistrarForncedor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegistrarForncedor.ButtonText = "Registrar Fornecedor";
            this.RegistrarForncedor.ButtonTextMarginLeft = 0;
            this.RegistrarForncedor.ColorContrastOnClick = 45;
            this.RegistrarForncedor.ColorContrastOnHover = 45;
            this.RegistrarForncedor.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.RegistrarForncedor.CustomizableEdges = borderEdges3;
            this.RegistrarForncedor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegistrarForncedor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegistrarForncedor.DisabledFillColor = System.Drawing.Color.Empty;
            this.RegistrarForncedor.DisabledForecolor = System.Drawing.Color.Empty;
            this.RegistrarForncedor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RegistrarForncedor.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.RegistrarForncedor.ForeColor = System.Drawing.Color.White;
            this.RegistrarForncedor.IconLeft = null;
            this.RegistrarForncedor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegistrarForncedor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegistrarForncedor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegistrarForncedor.IconMarginLeft = 11;
            this.RegistrarForncedor.IconPadding = 10;
            this.RegistrarForncedor.IconRight = null;
            this.RegistrarForncedor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegistrarForncedor.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.RegistrarForncedor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegistrarForncedor.IconSize = 25;
            this.RegistrarForncedor.IdleBorderColor = System.Drawing.Color.Empty;
            this.RegistrarForncedor.IdleBorderRadius = 0;
            this.RegistrarForncedor.IdleBorderThickness = 0;
            this.RegistrarForncedor.IdleFillColor = System.Drawing.Color.Empty;
            this.RegistrarForncedor.IdleIconLeftImage = null;
            this.RegistrarForncedor.IdleIconRightImage = null;
            this.RegistrarForncedor.IndicateFocus = false;
            this.RegistrarForncedor.Location = new System.Drawing.Point(130, 287);
            this.RegistrarForncedor.Name = "RegistrarForncedor";
            this.RegistrarForncedor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegistrarForncedor.OnDisabledState.BorderRadius = 23;
            this.RegistrarForncedor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegistrarForncedor.OnDisabledState.BorderThickness = 1;
            this.RegistrarForncedor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegistrarForncedor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegistrarForncedor.OnDisabledState.IconLeftImage = null;
            this.RegistrarForncedor.OnDisabledState.IconRightImage = null;
            this.RegistrarForncedor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.RegistrarForncedor.onHoverState.BorderRadius = 23;
            this.RegistrarForncedor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegistrarForncedor.onHoverState.BorderThickness = 1;
            this.RegistrarForncedor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.RegistrarForncedor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegistrarForncedor.onHoverState.IconLeftImage = null;
            this.RegistrarForncedor.onHoverState.IconRightImage = null;
            this.RegistrarForncedor.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.RegistrarForncedor.OnIdleState.BorderRadius = 23;
            this.RegistrarForncedor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegistrarForncedor.OnIdleState.BorderThickness = 1;
            this.RegistrarForncedor.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.RegistrarForncedor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegistrarForncedor.OnIdleState.IconLeftImage = null;
            this.RegistrarForncedor.OnIdleState.IconRightImage = null;
            this.RegistrarForncedor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegistrarForncedor.OnPressedState.BorderRadius = 23;
            this.RegistrarForncedor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegistrarForncedor.OnPressedState.BorderThickness = 1;
            this.RegistrarForncedor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegistrarForncedor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegistrarForncedor.OnPressedState.IconLeftImage = null;
            this.RegistrarForncedor.OnPressedState.IconRightImage = null;
            this.RegistrarForncedor.Size = new System.Drawing.Size(135, 35);
            this.RegistrarForncedor.TabIndex = 12;
            this.RegistrarForncedor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegistrarForncedor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegistrarForncedor.TextMarginLeft = 0;
            this.RegistrarForncedor.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegistrarForncedor.UseDefaultRadiusAndThickness = true;
            this.RegistrarForncedor.Click += new System.EventHandler(this.RegistrarForncedor_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(22, 80);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(29, 15);
            this.bunifuLabel2.TabIndex = 4;
            this.bunifuLabel2.Text = "Email";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(216, 146);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(25, 15);
            this.bunifuLabel3.TabIndex = 5;
            this.bunifuLabel3.Text = "Cnpj";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(130, 208);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(19, 15);
            this.bunifuLabel5.TabIndex = 7;
            this.bunifuLabel5.Text = "Cpf";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(22, 146);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(43, 15);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "telefone";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TabelasFornecedor
            // 
            this.TabelasFornecedor.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.TabelasFornecedor.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.TabelasFornecedor.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.TabelasFornecedor.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.TabelasFornecedor.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.TabelasFornecedor.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.TabelasFornecedor.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.TabelasFornecedor.ColumnHeadersHeight = 40;
            this.TabelasFornecedor.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.TabelasFornecedor.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.TabelasFornecedor.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.TabelasFornecedor.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.TabelasFornecedor.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.TabelasFornecedor.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.TabelasFornecedor.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.TabelasFornecedor.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.TabelasFornecedor.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.TabelasFornecedor.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.TabelasFornecedor.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.TabelasFornecedor.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.TabelasFornecedor.CurrentTheme.Name = null;
            this.TabelasFornecedor.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.TabelasFornecedor.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.TabelasFornecedor.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.TabelasFornecedor.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.TabelasFornecedor.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.TabelasFornecedor.DefaultCellStyle = dataGridViewCellStyle3;
            this.TabelasFornecedor.EnableHeadersVisualStyles = false;
            this.TabelasFornecedor.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.TabelasFornecedor.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.TabelasFornecedor.HeaderBgColor = System.Drawing.Color.Empty;
            this.TabelasFornecedor.HeaderForeColor = System.Drawing.Color.White;
            this.TabelasFornecedor.Location = new System.Drawing.Point(402, 0);
            this.TabelasFornecedor.Name = "TabelasFornecedor";
            this.TabelasFornecedor.RowHeadersVisible = false;
            this.TabelasFornecedor.RowTemplate.Height = 40;
            this.TabelasFornecedor.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.TabelasFornecedor.Size = new System.Drawing.Size(393, 450);
            this.TabelasFornecedor.TabIndex = 10;
            this.TabelasFornecedor.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.TabelasFornecedor.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.TabelasFornecedor_CellContentClick);
            // 
            // remover
            // 
            this.remover.AllowAnimations = true;
            this.remover.AllowMouseEffects = true;
            this.remover.AllowToggling = false;
            this.remover.AnimationSpeed = 200;
            this.remover.AutoGenerateColors = false;
            this.remover.AutoRoundBorders = false;
            this.remover.AutoSizeLeftIcon = true;
            this.remover.AutoSizeRightIcon = true;
            this.remover.BackColor = System.Drawing.Color.Transparent;
            this.remover.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.remover.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("remover.BackgroundImage")));
            this.remover.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.ButtonText = "Remover";
            this.remover.ButtonTextMarginLeft = 0;
            this.remover.ColorContrastOnClick = 45;
            this.remover.ColorContrastOnHover = 45;
            this.remover.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.remover.CustomizableEdges = borderEdges1;
            this.remover.DialogResult = System.Windows.Forms.DialogResult.None;
            this.remover.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.remover.DisabledFillColor = System.Drawing.Color.Empty;
            this.remover.DisabledForecolor = System.Drawing.Color.Empty;
            this.remover.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.remover.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.remover.ForeColor = System.Drawing.Color.White;
            this.remover.IconLeft = null;
            this.remover.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.remover.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.remover.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.remover.IconMarginLeft = 11;
            this.remover.IconPadding = 10;
            this.remover.IconRight = null;
            this.remover.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.remover.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.remover.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.remover.IconSize = 25;
            this.remover.IdleBorderColor = System.Drawing.Color.Empty;
            this.remover.IdleBorderRadius = 0;
            this.remover.IdleBorderThickness = 0;
            this.remover.IdleFillColor = System.Drawing.Color.Empty;
            this.remover.IdleIconLeftImage = null;
            this.remover.IdleIconRightImage = null;
            this.remover.IndicateFocus = false;
            this.remover.Location = new System.Drawing.Point(211, 328);
            this.remover.Name = "remover";
            this.remover.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.remover.OnDisabledState.BorderRadius = 17;
            this.remover.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnDisabledState.BorderThickness = 1;
            this.remover.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.remover.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.remover.OnDisabledState.IconLeftImage = null;
            this.remover.OnDisabledState.IconRightImage = null;
            this.remover.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.remover.onHoverState.BorderRadius = 17;
            this.remover.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.onHoverState.BorderThickness = 1;
            this.remover.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.remover.onHoverState.ForeColor = System.Drawing.Color.White;
            this.remover.onHoverState.IconLeftImage = null;
            this.remover.onHoverState.IconRightImage = null;
            this.remover.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.remover.OnIdleState.BorderRadius = 17;
            this.remover.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnIdleState.BorderThickness = 1;
            this.remover.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.remover.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.remover.OnIdleState.IconLeftImage = null;
            this.remover.OnIdleState.IconRightImage = null;
            this.remover.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.remover.OnPressedState.BorderRadius = 17;
            this.remover.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnPressedState.BorderThickness = 1;
            this.remover.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.remover.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.remover.OnPressedState.IconLeftImage = null;
            this.remover.OnPressedState.IconRightImage = null;
            this.remover.Size = new System.Drawing.Size(54, 30);
            this.remover.TabIndex = 24;
            this.remover.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.remover.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.remover.TextMarginLeft = 0;
            this.remover.TextPadding = new System.Windows.Forms.Padding(0);
            this.remover.UseDefaultRadiusAndThickness = true;
            this.remover.Click += new System.EventHandler(this.remover_Click);
            // 
            // Fornecedor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.InactiveCaption;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.TabelasFornecedor);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "Fornecedor";
            this.Text = "Fornecedor";
            this.Load += new System.EventHandler(this.Fornecedor_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TabelasFornecedor)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RegistrarForncedor;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox enderecoFornecedorTxt;
        private Bunifu.UI.WinForms.BunifuTextBox cnpjFornecedorTxt;
        private Bunifu.UI.WinForms.BunifuTextBox cpfFornecdorTxt;
        private Bunifu.UI.WinForms.BunifuTextBox telfornecedorTxt;
        private Bunifu.UI.WinForms.BunifuTextBox emailFornecedorTxt;
        private Bunifu.UI.WinForms.BunifuDatePicker calendarioNascimento;
        private Bunifu.UI.WinForms.BunifuTextBox nomefornecedorTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton voltarbotao;
        private Bunifu.UI.WinForms.BunifuDataGridView TabelasFornecedor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton remover;
    }
}