
namespace gf_materiais.forms
{
    partial class TeladeEstoque
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TeladeEstoque));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.qntatualTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.qntmaxTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.produtoTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.qntminTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.remover = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.registrotxt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.voltarbotao = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TabelaProdutos = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TabelaProdutos)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.LightSlateGray;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.qntatualTxt);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.qntmaxTxt);
            this.bunifuPanel1.Controls.Add(this.produtoTxt);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.qntminTxt);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(800, 55);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // qntatualTxt
            // 
            this.qntatualTxt.AcceptsReturn = false;
            this.qntatualTxt.AcceptsTab = false;
            this.qntatualTxt.AnimationSpeed = 200;
            this.qntatualTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.qntatualTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.qntatualTxt.AutoSizeHeight = true;
            this.qntatualTxt.BackColor = System.Drawing.Color.Transparent;
            this.qntatualTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qntatualTxt.BackgroundImage")));
            this.qntatualTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.qntatualTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qntatualTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.qntatualTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.qntatualTxt.BorderRadius = 23;
            this.qntatualTxt.BorderThickness = 1;
            this.qntatualTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.qntatualTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.qntatualTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.qntatualTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.qntatualTxt.DefaultText = "";
            this.qntatualTxt.FillColor = System.Drawing.Color.White;
            this.qntatualTxt.HideSelection = true;
            this.qntatualTxt.IconLeft = null;
            this.qntatualTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntatualTxt.IconPadding = 10;
            this.qntatualTxt.IconRight = null;
            this.qntatualTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntatualTxt.Lines = new string[0];
            this.qntatualTxt.Location = new System.Drawing.Point(632, 12);
            this.qntatualTxt.MaxLength = 32767;
            this.qntatualTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.qntatualTxt.Modified = false;
            this.qntatualTxt.Multiline = false;
            this.qntatualTxt.Name = "qntatualTxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntatualTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.qntatualTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntatualTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntatualTxt.OnIdleState = stateProperties4;
            this.qntatualTxt.Padding = new System.Windows.Forms.Padding(3);
            this.qntatualTxt.PasswordChar = '\0';
            this.qntatualTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.qntatualTxt.PlaceholderText = "Qnt Atual";
            this.qntatualTxt.ReadOnly = false;
            this.qntatualTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.qntatualTxt.SelectedText = "";
            this.qntatualTxt.SelectionLength = 0;
            this.qntatualTxt.SelectionStart = 0;
            this.qntatualTxt.ShortcutsEnabled = true;
            this.qntatualTxt.Size = new System.Drawing.Size(101, 30);
            this.qntatualTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.qntatualTxt.TabIndex = 9;
            this.qntatualTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.qntatualTxt.TextMarginBottom = 0;
            this.qntatualTxt.TextMarginLeft = 3;
            this.qntatualTxt.TextMarginTop = 1;
            this.qntatualTxt.TextPlaceholder = "Qnt Atual";
            this.qntatualTxt.UseSystemPasswordChar = false;
            this.qntatualTxt.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(575, 21);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(51, 15);
            this.bunifuLabel4.TabIndex = 8;
            this.bunifuLabel4.Text = "Qnt Atual";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // qntmaxTxt
            // 
            this.qntmaxTxt.AcceptsReturn = false;
            this.qntmaxTxt.AcceptsTab = false;
            this.qntmaxTxt.AnimationSpeed = 200;
            this.qntmaxTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.qntmaxTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.qntmaxTxt.AutoSizeHeight = true;
            this.qntmaxTxt.BackColor = System.Drawing.Color.Transparent;
            this.qntmaxTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qntmaxTxt.BackgroundImage")));
            this.qntmaxTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.qntmaxTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qntmaxTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.qntmaxTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.qntmaxTxt.BorderRadius = 23;
            this.qntmaxTxt.BorderThickness = 1;
            this.qntmaxTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.qntmaxTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.qntmaxTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.qntmaxTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.qntmaxTxt.DefaultText = "";
            this.qntmaxTxt.FillColor = System.Drawing.Color.White;
            this.qntmaxTxt.HideSelection = true;
            this.qntmaxTxt.IconLeft = null;
            this.qntmaxTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntmaxTxt.IconPadding = 10;
            this.qntmaxTxt.IconRight = null;
            this.qntmaxTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntmaxTxt.Lines = new string[0];
            this.qntmaxTxt.Location = new System.Drawing.Point(455, 12);
            this.qntmaxTxt.MaxLength = 32767;
            this.qntmaxTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.qntmaxTxt.Modified = false;
            this.qntmaxTxt.Multiline = false;
            this.qntmaxTxt.Name = "qntmaxTxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntmaxTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.qntmaxTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntmaxTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntmaxTxt.OnIdleState = stateProperties8;
            this.qntmaxTxt.Padding = new System.Windows.Forms.Padding(3);
            this.qntmaxTxt.PasswordChar = '\0';
            this.qntmaxTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.qntmaxTxt.PlaceholderText = "Qnt maxima";
            this.qntmaxTxt.ReadOnly = false;
            this.qntmaxTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.qntmaxTxt.SelectedText = "";
            this.qntmaxTxt.SelectionLength = 0;
            this.qntmaxTxt.SelectionStart = 0;
            this.qntmaxTxt.ShortcutsEnabled = true;
            this.qntmaxTxt.Size = new System.Drawing.Size(101, 30);
            this.qntmaxTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.qntmaxTxt.TabIndex = 6;
            this.qntmaxTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.qntmaxTxt.TextMarginBottom = 0;
            this.qntmaxTxt.TextMarginLeft = 3;
            this.qntmaxTxt.TextMarginTop = 1;
            this.qntmaxTxt.TextPlaceholder = "Qnt maxima";
            this.qntmaxTxt.UseSystemPasswordChar = false;
            this.qntmaxTxt.WordWrap = true;
            // 
            // produtoTxt
            // 
            this.produtoTxt.AcceptsReturn = false;
            this.produtoTxt.AcceptsTab = false;
            this.produtoTxt.AnimationSpeed = 200;
            this.produtoTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.produtoTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.produtoTxt.AutoSizeHeight = true;
            this.produtoTxt.BackColor = System.Drawing.Color.Transparent;
            this.produtoTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("produtoTxt.BackgroundImage")));
            this.produtoTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.produtoTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.produtoTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.produtoTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.produtoTxt.BorderRadius = 23;
            this.produtoTxt.BorderThickness = 1;
            this.produtoTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.produtoTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.produtoTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.produtoTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.produtoTxt.DefaultText = "";
            this.produtoTxt.FillColor = System.Drawing.Color.White;
            this.produtoTxt.HideSelection = true;
            this.produtoTxt.IconLeft = null;
            this.produtoTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.produtoTxt.IconPadding = 10;
            this.produtoTxt.IconRight = null;
            this.produtoTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.produtoTxt.Lines = new string[0];
            this.produtoTxt.Location = new System.Drawing.Point(61, 12);
            this.produtoTxt.MaxLength = 32767;
            this.produtoTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.produtoTxt.Modified = false;
            this.produtoTxt.Multiline = false;
            this.produtoTxt.Name = "produtoTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.produtoTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.produtoTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.produtoTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.produtoTxt.OnIdleState = stateProperties12;
            this.produtoTxt.Padding = new System.Windows.Forms.Padding(3);
            this.produtoTxt.PasswordChar = '\0';
            this.produtoTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.produtoTxt.PlaceholderText = "Cadastre o Produto";
            this.produtoTxt.ReadOnly = false;
            this.produtoTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.produtoTxt.SelectedText = "";
            this.produtoTxt.SelectionLength = 0;
            this.produtoTxt.SelectionStart = 0;
            this.produtoTxt.ShortcutsEnabled = true;
            this.produtoTxt.Size = new System.Drawing.Size(135, 30);
            this.produtoTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.produtoTxt.TabIndex = 7;
            this.produtoTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.produtoTxt.TextMarginBottom = 0;
            this.produtoTxt.TextMarginLeft = 3;
            this.produtoTxt.TextMarginTop = 1;
            this.produtoTxt.TextPlaceholder = "Cadastre o Produto";
            this.produtoTxt.UseSystemPasswordChar = false;
            this.produtoTxt.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(403, 21);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(46, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Qnt Max";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // qntminTxt
            // 
            this.qntminTxt.AcceptsReturn = false;
            this.qntminTxt.AcceptsTab = false;
            this.qntminTxt.AnimationSpeed = 200;
            this.qntminTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.qntminTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.qntminTxt.AutoSizeHeight = true;
            this.qntminTxt.BackColor = System.Drawing.Color.Transparent;
            this.qntminTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qntminTxt.BackgroundImage")));
            this.qntminTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.qntminTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qntminTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.qntminTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.qntminTxt.BorderRadius = 23;
            this.qntminTxt.BorderThickness = 1;
            this.qntminTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.qntminTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.qntminTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.qntminTxt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.qntminTxt.DefaultText = "";
            this.qntminTxt.FillColor = System.Drawing.Color.White;
            this.qntminTxt.HideSelection = true;
            this.qntminTxt.IconLeft = null;
            this.qntminTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntminTxt.IconPadding = 10;
            this.qntminTxt.IconRight = null;
            this.qntminTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.qntminTxt.Lines = new string[0];
            this.qntminTxt.Location = new System.Drawing.Point(281, 12);
            this.qntminTxt.MaxLength = 32767;
            this.qntminTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.qntminTxt.Modified = false;
            this.qntminTxt.Multiline = false;
            this.qntminTxt.Name = "qntminTxt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntminTxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.qntminTxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntminTxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qntminTxt.OnIdleState = stateProperties16;
            this.qntminTxt.Padding = new System.Windows.Forms.Padding(3);
            this.qntminTxt.PasswordChar = '\0';
            this.qntminTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.qntminTxt.PlaceholderText = "Qnt minima";
            this.qntminTxt.ReadOnly = false;
            this.qntminTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.qntminTxt.SelectedText = "";
            this.qntminTxt.SelectionLength = 0;
            this.qntminTxt.SelectionStart = 0;
            this.qntminTxt.ShortcutsEnabled = true;
            this.qntminTxt.Size = new System.Drawing.Size(101, 30);
            this.qntminTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.qntminTxt.TabIndex = 5;
            this.qntminTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.qntminTxt.TextMarginBottom = 0;
            this.qntminTxt.TextMarginLeft = 3;
            this.qntminTxt.TextMarginTop = 1;
            this.qntminTxt.TextPlaceholder = "Qnt minima";
            this.qntminTxt.UseSystemPasswordChar = false;
            this.qntminTxt.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 21);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(43, 15);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Produto";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(231, 21);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(44, 15);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Qnt Min";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.LightSlateGray;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.remover);
            this.bunifuPanel2.Controls.Add(this.registrotxt);
            this.bunifuPanel2.Controls.Add(this.voltarbotao);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuPanel2.Location = new System.Drawing.Point(729, 55);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(71, 395);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // remover
            // 
            this.remover.AllowAnimations = true;
            this.remover.AllowMouseEffects = true;
            this.remover.AllowToggling = false;
            this.remover.AnimationSpeed = 200;
            this.remover.AutoGenerateColors = false;
            this.remover.AutoRoundBorders = false;
            this.remover.AutoSizeLeftIcon = true;
            this.remover.AutoSizeRightIcon = true;
            this.remover.BackColor = System.Drawing.Color.Transparent;
            this.remover.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.remover.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("remover.BackgroundImage")));
            this.remover.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.ButtonText = "Remover";
            this.remover.ButtonTextMarginLeft = 0;
            this.remover.ColorContrastOnClick = 45;
            this.remover.ColorContrastOnHover = 45;
            this.remover.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.remover.CustomizableEdges = borderEdges1;
            this.remover.DialogResult = System.Windows.Forms.DialogResult.None;
            this.remover.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.remover.DisabledFillColor = System.Drawing.Color.Empty;
            this.remover.DisabledForecolor = System.Drawing.Color.Empty;
            this.remover.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.remover.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.remover.ForeColor = System.Drawing.Color.White;
            this.remover.IconLeft = null;
            this.remover.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.remover.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.remover.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.remover.IconMarginLeft = 11;
            this.remover.IconPadding = 10;
            this.remover.IconRight = null;
            this.remover.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.remover.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.remover.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.remover.IconSize = 25;
            this.remover.IdleBorderColor = System.Drawing.Color.Empty;
            this.remover.IdleBorderRadius = 0;
            this.remover.IdleBorderThickness = 0;
            this.remover.IdleFillColor = System.Drawing.Color.Empty;
            this.remover.IdleIconLeftImage = null;
            this.remover.IdleIconRightImage = null;
            this.remover.IndicateFocus = false;
            this.remover.Location = new System.Drawing.Point(12, 67);
            this.remover.Name = "remover";
            this.remover.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.remover.OnDisabledState.BorderRadius = 17;
            this.remover.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnDisabledState.BorderThickness = 1;
            this.remover.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.remover.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.remover.OnDisabledState.IconLeftImage = null;
            this.remover.OnDisabledState.IconRightImage = null;
            this.remover.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.remover.onHoverState.BorderRadius = 17;
            this.remover.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.onHoverState.BorderThickness = 1;
            this.remover.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.remover.onHoverState.ForeColor = System.Drawing.Color.White;
            this.remover.onHoverState.IconLeftImage = null;
            this.remover.onHoverState.IconRightImage = null;
            this.remover.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.remover.OnIdleState.BorderRadius = 17;
            this.remover.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnIdleState.BorderThickness = 1;
            this.remover.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.remover.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.remover.OnIdleState.IconLeftImage = null;
            this.remover.OnIdleState.IconRightImage = null;
            this.remover.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.remover.OnPressedState.BorderRadius = 17;
            this.remover.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remover.OnPressedState.BorderThickness = 1;
            this.remover.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.remover.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.remover.OnPressedState.IconLeftImage = null;
            this.remover.OnPressedState.IconRightImage = null;
            this.remover.Size = new System.Drawing.Size(51, 26);
            this.remover.TabIndex = 3;
            this.remover.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.remover.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.remover.TextMarginLeft = 0;
            this.remover.TextPadding = new System.Windows.Forms.Padding(0);
            this.remover.UseDefaultRadiusAndThickness = true;
            this.remover.Click += new System.EventHandler(this.remover_Click);
            // 
            // registrotxt
            // 
            this.registrotxt.AllowAnimations = true;
            this.registrotxt.AllowMouseEffects = true;
            this.registrotxt.AllowToggling = false;
            this.registrotxt.AnimationSpeed = 200;
            this.registrotxt.AutoGenerateColors = false;
            this.registrotxt.AutoRoundBorders = false;
            this.registrotxt.AutoSizeLeftIcon = true;
            this.registrotxt.AutoSizeRightIcon = true;
            this.registrotxt.BackColor = System.Drawing.Color.Transparent;
            this.registrotxt.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.registrotxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("registrotxt.BackgroundImage")));
            this.registrotxt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registrotxt.ButtonText = "Registrar";
            this.registrotxt.ButtonTextMarginLeft = 0;
            this.registrotxt.ColorContrastOnClick = 45;
            this.registrotxt.ColorContrastOnHover = 45;
            this.registrotxt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.registrotxt.CustomizableEdges = borderEdges2;
            this.registrotxt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.registrotxt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.registrotxt.DisabledFillColor = System.Drawing.Color.Empty;
            this.registrotxt.DisabledForecolor = System.Drawing.Color.Empty;
            this.registrotxt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.registrotxt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.registrotxt.ForeColor = System.Drawing.Color.White;
            this.registrotxt.IconLeft = null;
            this.registrotxt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.registrotxt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.registrotxt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.registrotxt.IconMarginLeft = 11;
            this.registrotxt.IconPadding = 10;
            this.registrotxt.IconRight = null;
            this.registrotxt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.registrotxt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.registrotxt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.registrotxt.IconSize = 25;
            this.registrotxt.IdleBorderColor = System.Drawing.Color.Empty;
            this.registrotxt.IdleBorderRadius = 0;
            this.registrotxt.IdleBorderThickness = 0;
            this.registrotxt.IdleFillColor = System.Drawing.Color.Empty;
            this.registrotxt.IdleIconLeftImage = null;
            this.registrotxt.IdleIconRightImage = null;
            this.registrotxt.IndicateFocus = false;
            this.registrotxt.Location = new System.Drawing.Point(12, 22);
            this.registrotxt.Name = "registrotxt";
            this.registrotxt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.registrotxt.OnDisabledState.BorderRadius = 17;
            this.registrotxt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registrotxt.OnDisabledState.BorderThickness = 1;
            this.registrotxt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.registrotxt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.registrotxt.OnDisabledState.IconLeftImage = null;
            this.registrotxt.OnDisabledState.IconRightImage = null;
            this.registrotxt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.registrotxt.onHoverState.BorderRadius = 17;
            this.registrotxt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registrotxt.onHoverState.BorderThickness = 1;
            this.registrotxt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.registrotxt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.registrotxt.onHoverState.IconLeftImage = null;
            this.registrotxt.onHoverState.IconRightImage = null;
            this.registrotxt.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.registrotxt.OnIdleState.BorderRadius = 17;
            this.registrotxt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registrotxt.OnIdleState.BorderThickness = 1;
            this.registrotxt.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.registrotxt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.registrotxt.OnIdleState.IconLeftImage = null;
            this.registrotxt.OnIdleState.IconRightImage = null;
            this.registrotxt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registrotxt.OnPressedState.BorderRadius = 17;
            this.registrotxt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registrotxt.OnPressedState.BorderThickness = 1;
            this.registrotxt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registrotxt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.registrotxt.OnPressedState.IconLeftImage = null;
            this.registrotxt.OnPressedState.IconRightImage = null;
            this.registrotxt.Size = new System.Drawing.Size(51, 30);
            this.registrotxt.TabIndex = 1;
            this.registrotxt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.registrotxt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.registrotxt.TextMarginLeft = 0;
            this.registrotxt.TextPadding = new System.Windows.Forms.Padding(0);
            this.registrotxt.UseDefaultRadiusAndThickness = true;
            this.registrotxt.Click += new System.EventHandler(this.registrotxt_Click);
            // 
            // voltarbotao
            // 
            this.voltarbotao.AllowAnimations = true;
            this.voltarbotao.AllowMouseEffects = true;
            this.voltarbotao.AllowToggling = false;
            this.voltarbotao.AnimationSpeed = 200;
            this.voltarbotao.AutoGenerateColors = false;
            this.voltarbotao.AutoRoundBorders = false;
            this.voltarbotao.AutoSizeLeftIcon = true;
            this.voltarbotao.AutoSizeRightIcon = true;
            this.voltarbotao.BackColor = System.Drawing.Color.Transparent;
            this.voltarbotao.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.voltarbotao.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("voltarbotao.BackgroundImage")));
            this.voltarbotao.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.ButtonText = "Voltar";
            this.voltarbotao.ButtonTextMarginLeft = 0;
            this.voltarbotao.ColorContrastOnClick = 45;
            this.voltarbotao.ColorContrastOnHover = 45;
            this.voltarbotao.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.voltarbotao.CustomizableEdges = borderEdges3;
            this.voltarbotao.DialogResult = System.Windows.Forms.DialogResult.None;
            this.voltarbotao.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.voltarbotao.DisabledFillColor = System.Drawing.Color.Empty;
            this.voltarbotao.DisabledForecolor = System.Drawing.Color.Empty;
            this.voltarbotao.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.voltarbotao.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.voltarbotao.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.IconLeft = null;
            this.voltarbotao.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.voltarbotao.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.voltarbotao.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.voltarbotao.IconMarginLeft = 11;
            this.voltarbotao.IconPadding = 10;
            this.voltarbotao.IconRight = null;
            this.voltarbotao.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.voltarbotao.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.voltarbotao.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.voltarbotao.IconSize = 25;
            this.voltarbotao.IdleBorderColor = System.Drawing.Color.Empty;
            this.voltarbotao.IdleBorderRadius = 0;
            this.voltarbotao.IdleBorderThickness = 0;
            this.voltarbotao.IdleFillColor = System.Drawing.Color.Empty;
            this.voltarbotao.IdleIconLeftImage = null;
            this.voltarbotao.IdleIconRightImage = null;
            this.voltarbotao.IndicateFocus = false;
            this.voltarbotao.Location = new System.Drawing.Point(12, 353);
            this.voltarbotao.Name = "voltarbotao";
            this.voltarbotao.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.voltarbotao.OnDisabledState.BorderRadius = 17;
            this.voltarbotao.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnDisabledState.BorderThickness = 1;
            this.voltarbotao.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.voltarbotao.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.voltarbotao.OnDisabledState.IconLeftImage = null;
            this.voltarbotao.OnDisabledState.IconRightImage = null;
            this.voltarbotao.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.voltarbotao.onHoverState.BorderRadius = 17;
            this.voltarbotao.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.onHoverState.BorderThickness = 1;
            this.voltarbotao.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.voltarbotao.onHoverState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.onHoverState.IconLeftImage = null;
            this.voltarbotao.onHoverState.IconRightImage = null;
            this.voltarbotao.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.voltarbotao.OnIdleState.BorderRadius = 17;
            this.voltarbotao.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnIdleState.BorderThickness = 1;
            this.voltarbotao.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.voltarbotao.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.OnIdleState.IconLeftImage = null;
            this.voltarbotao.OnIdleState.IconRightImage = null;
            this.voltarbotao.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.voltarbotao.OnPressedState.BorderRadius = 17;
            this.voltarbotao.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.voltarbotao.OnPressedState.BorderThickness = 1;
            this.voltarbotao.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.voltarbotao.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.voltarbotao.OnPressedState.IconLeftImage = null;
            this.voltarbotao.OnPressedState.IconRightImage = null;
            this.voltarbotao.Size = new System.Drawing.Size(51, 30);
            this.voltarbotao.TabIndex = 2;
            this.voltarbotao.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.voltarbotao.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.voltarbotao.TextMarginLeft = 0;
            this.voltarbotao.TextPadding = new System.Windows.Forms.Padding(0);
            this.voltarbotao.UseDefaultRadiusAndThickness = true;
            this.voltarbotao.Click += new System.EventHandler(this.voltarbotao_Click);
            // 
            // TabelaProdutos
            // 
            this.TabelaProdutos.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.TabelaProdutos.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.TabelaProdutos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.TabelaProdutos.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.TabelaProdutos.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.TabelaProdutos.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.TabelaProdutos.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.TabelaProdutos.ColumnHeadersHeight = 40;
            this.TabelaProdutos.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.TabelaProdutos.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.TabelaProdutos.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.TabelaProdutos.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.TabelaProdutos.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.TabelaProdutos.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.TabelaProdutos.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.TabelaProdutos.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.TabelaProdutos.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.TabelaProdutos.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.TabelaProdutos.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.TabelaProdutos.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.TabelaProdutos.CurrentTheme.Name = null;
            this.TabelaProdutos.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.TabelaProdutos.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.TabelaProdutos.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.TabelaProdutos.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.TabelaProdutos.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.TabelaProdutos.DefaultCellStyle = dataGridViewCellStyle3;
            this.TabelaProdutos.EnableHeadersVisualStyles = false;
            this.TabelaProdutos.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.TabelaProdutos.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.TabelaProdutos.HeaderBgColor = System.Drawing.Color.Empty;
            this.TabelaProdutos.HeaderForeColor = System.Drawing.Color.White;
            this.TabelaProdutos.Location = new System.Drawing.Point(0, 55);
            this.TabelaProdutos.Name = "TabelaProdutos";
            this.TabelaProdutos.RowHeadersVisible = false;
            this.TabelaProdutos.RowTemplate.Height = 40;
            this.TabelaProdutos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.TabelaProdutos.Size = new System.Drawing.Size(733, 395);
            this.TabelaProdutos.TabIndex = 2;
            this.TabelaProdutos.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.TabelaProdutos.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellContentClick);
            // 
            // TeladeEstoque
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.InactiveCaption;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.TabelaProdutos);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "TeladeEstoque";
            this.Text = "TeladeEstoque";
            this.Load += new System.EventHandler(this.tela_load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.TabelaProdutos)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton registrotxt;
        private Bunifu.UI.WinForms.BunifuTextBox qntmaxTxt;
        private Bunifu.UI.WinForms.BunifuTextBox produtoTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox qntminTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox qntatualTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton voltarbotao;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton remover;
        private Bunifu.UI.WinForms.BunifuDataGridView TabelaProdutos;
    }
}